/**
 * Cloudflare Tunnel Discovery and Status Service
 * File: src/lib/tunnel.ts
 *
 * Provides a unified source of truth for Cloudflare Tunnel discovery,
 * daemon health diagnostics, edge location, and latency telemetry.
 */

import fs from "node:fs/promises";
import path from "node:path";

export interface TunnelMetrics {
  haConnections: number;
  edgeLocation: string;
  quicSmoothedRttMs: number;
  totalRegistrations: number;
  metricsReachable: boolean;
}

export interface TunnelStatus {
  active: boolean;
  public_url: string;
  provider: "cloudflare" | "custom" | "fallback";
  edge_location: string;
  protocol: string;
  encryption: string;
  connector_id: string;
  updated_at: string;
  source: "env" | "tunnel_info.json" | "public_url.txt" | "fallback";
  metrics?: TunnelMetrics;
}

const CANONICAL_FALLBACK_URL =
  "https://vocational-damages-calculated-are.trycloudflare.com";

let cachedStatus: TunnelStatus | null = null;
let cacheExpiresAt = 0;
const CACHE_TTL_MS = 10_000; // 10 seconds TTL

/**
 * Queries cloudflared local Prometheus metrics server (127.0.0.1:20241)
 * to inspect live HA connection status and smoothed QUIC RTT.
 */
async function queryDaemonMetrics(): Promise<TunnelMetrics> {
  const defaultMetrics: TunnelMetrics = {
    haConnections: 0,
    edgeLocation: "unknown",
    quicSmoothedRttMs: 0,
    totalRegistrations: 0,
    metricsReachable: false,
  };

  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 500);

    const res = await fetch("http://127.0.0.1:20241/metrics", {
      signal: controller.signal,
      headers: { Accept: "text/plain" },
    });
    clearTimeout(timeout);

    if (!res.ok) return defaultMetrics;
    const text = await res.text();

    defaultMetrics.metricsReachable = true;

    // Parse ha_connections
    const haMatch = text.match(/cloudflared_tunnel_ha_connections\s+(\d+)/);
    if (haMatch) defaultMetrics.haConnections = parseInt(haMatch[1], 10);

    // Parse edge_location
    const locMatch = text.match(/edge_location="([^"]+)"/);
    if (locMatch) defaultMetrics.edgeLocation = locMatch[1];

    // Parse quic_smoothed_rtt
    const rttMatch = text.match(/quic_client_smoothed_rtt(?:\{[^}]*\})?\s+(\d+)/);
    if (rttMatch) defaultMetrics.quicSmoothedRttMs = parseInt(rttMatch[1], 10);

    // Parse tunnel registrations
    const regMatch = text.match(/cloudflared_tunnel_tunnel_register_success(?:\{[^}]*\})?\s+(\d+)/);
    if (regMatch) defaultMetrics.totalRegistrations = parseInt(regMatch[1], 10);

    return defaultMetrics;
  } catch {
    return defaultMetrics;
  }
}

/**
 * Retrieves the comprehensive Cloudflare Tunnel status.
 */
export async function getTunnelStatus(forceRefresh = false): Promise<TunnelStatus> {
  const now = Date.now();
  if (!forceRefresh && cachedStatus && now < cacheExpiresAt) {
    return cachedStatus;
  }

  // 1. Environment Variable Override
  const envUrl =
    process.env.CLOUDFLARE_TUNNEL_URL ||
    process.env.TUNNEL_URL ||
    process.env.NEXT_PUBLIC_TUNNEL_URL;

  if (envUrl && envUrl.trim().startsWith("http")) {
    const metrics = await queryDaemonMetrics();
    const status: TunnelStatus = {
      active: true,
      public_url: envUrl.trim(),
      provider: "cloudflare",
      edge_location: metrics.edgeLocation !== "unknown" ? metrics.edgeLocation.toUpperCase() : "ENV_CONFIGURED",
      protocol: "QUIC / HTTP/2",
      encryption: "Edge TLS 1.3 / Post-Quantum",
      connector_id: "",
      updated_at: new Date().toISOString(),
      source: "env",
      metrics,
    };
    cachedStatus = status;
    cacheExpiresAt = now + CACHE_TTL_MS;
    return status;
  }

  // 2. Read tunnel_info.json generated by scripts/cloudflare_tunnel.sh
  const jsonPath = path.join(process.cwd(), "tunnel_info.json");
  try {
    const raw = await fs.readFile(jsonPath, "utf-8");
    const parsed = JSON.parse(raw);
    if (parsed.public_url && parsed.public_url.startsWith("http")) {
      const metrics = await queryDaemonMetrics();
      const status: TunnelStatus = {
        active: metrics.metricsReachable ? metrics.haConnections > 0 : Boolean(parsed.active ?? true),
        public_url: parsed.public_url.trim(),
        provider: "cloudflare",
        edge_location: parsed.edge_location || (metrics.edgeLocation !== "unknown" ? metrics.edgeLocation : "JNB (Johannesburg)"),
        protocol: parsed.protocol || "QUIC / HTTP/2",
        encryption: parsed.encryption || "Edge TLS 1.3 / Post-Quantum",
        connector_id: parsed.connector_id || "",
        updated_at: parsed.updated_at || new Date().toISOString(),
        source: "tunnel_info.json",
        metrics,
      };
      cachedStatus = status;
      cacheExpiresAt = now + CACHE_TTL_MS;
      return status;
    }
  } catch {
    // Proceed to fallback
  }

  // 3. Read public_url.txt generated by scripts/cloudflare_tunnel.sh
  const txtPath = path.join(process.cwd(), "public_url.txt");
  try {
    const raw = (await fs.readFile(txtPath, "utf-8")).trim();
    if (raw.startsWith("http")) {
      const metrics = await queryDaemonMetrics();
      const status: TunnelStatus = {
        active: metrics.metricsReachable ? metrics.haConnections > 0 : true,
        public_url: raw,
        provider: "cloudflare",
        edge_location: metrics.edgeLocation !== "unknown" ? metrics.edgeLocation : "JNB (Johannesburg)",
        protocol: "QUIC / HTTP/2",
        encryption: "Edge TLS 1.3 / Post-Quantum",
        connector_id: "",
        updated_at: new Date().toISOString(),
        source: "public_url.txt",
        metrics,
      };
      cachedStatus = status;
      cacheExpiresAt = now + CACHE_TTL_MS;
      return status;
    }
  } catch {
    // Proceed to canonical fallback
  }

  // 4. Canonical Default Fallback
  const metrics = await queryDaemonMetrics();
  const status: TunnelStatus = {
    active: metrics.metricsReachable && metrics.haConnections > 0,
    public_url: CANONICAL_FALLBACK_URL,
    provider: "cloudflare",
    edge_location: "JNB (Johannesburg)",
    protocol: "QUIC / HTTP/2",
    encryption: "Edge TLS 1.3 / Post-Quantum",
    connector_id: "",
    updated_at: new Date().toISOString(),
    source: "fallback",
    metrics,
  };

  cachedStatus = status;
  cacheExpiresAt = now + CACHE_TTL_MS;
  return status;
}

/**
 * Convenience helper returning just the active public tunnel URL.
 */
export async function getTunnelUrl(): Promise<string> {
  const status = await getTunnelStatus();
  return status.public_url;
}
