import prisma from "../../src/lib/prisma";

export interface TestResult {
  name: string;
  passed: boolean;
  error?: string;
  durationMs: number;
}

export type TestFn = () => Promise<void> | void;

export class TestSuite {
  name: string;
  tests: { name: string; fn: TestFn }[] = [];

  constructor(name: string) {
    this.name = name;
  }

  test(name: string, fn: TestFn) {
    this.tests.push({ name, fn });
  }

  async run(): Promise<{ name: string; results: TestResult[]; passed: number; failed: number }> {
    const results: TestResult[] = [];
    let passed = 0;
    let failed = 0;

    for (const t of this.tests) {
      const start = Date.now();
      try {
        await t.fn();
        const duration = Date.now() - start;
        results.push({ name: t.name, passed: true, durationMs: duration });
        passed++;
      } catch (err) {
        const duration = Date.now() - start;
        results.push({
          name: t.name,
          passed: false,
          error: err instanceof Error ? err.stack || err.message : String(err),
          durationMs: duration,
        });
        failed++;
      }
    }

    return { name: this.name, results, passed, failed };
  }
}

export function assert(condition: boolean, message: string) {
  if (!condition) {
    throw new Error(`Assertion Failed: ${message}`);
  }
}

export function assertEqual<T>(actual: T, expected: T, message?: string) {
  if (actual !== expected) {
    throw new Error(
      `Assertion Failed: Expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}. ${message || ""}`
    );
  }
}

export function assertIncludes(haystack: string | null | undefined, needle: string, message?: string) {
  if (!haystack || !haystack.includes(needle)) {
    throw new Error(
      `Assertion Failed: Expected string to include '${needle}', but got '${haystack}'. ${message || ""}`
    );
  }
}

export async function setupTestData() {
  // Ensure basic site settings and test records exist
  await prisma.site_settings.upsert({
    where: { key: "system_lockdown" },
    create: { key: "system_lockdown", value: "false" },
    update: { value: "false" },
  });
}

/**
 * Purge test pollution from SQLite database while strictly preserving baseline seed data.
 * Executes in reverse-topological foreign key order.
 */
export async function cleanupTestData() {
  try {
    // 1. Key custody logs (all are test artifacts)
    await prisma.key_custody_logs.deleteMany({});

    // 2. Keys (all are test artifacts)
    await prisma.keys.deleteMany({});

    // 3. Notifications created during test scans (id > 10)
    await prisma.notifications.deleteMany({
      where: { id: { gt: 10 } },
    });

    // 4. Approvals generated by test scans (id > 4 or matching test prefixes)
    await prisma.approvals.deleteMany({
      where: {
        OR: [
          { id: { gt: 4 } },
          { details: { contains: "UNREG_TAG_" } },
          { details: { contains: "TEST_" } },
          { details: { contains: "CHAL_" } },
        ],
      },
    });

    // 5. Gate logs generated during test scans (id > 14)
    await prisma.gate_logs.deleteMany({
      where: { id: { gt: 14 } },
    });

    // 6. Visitors generated during combinatorial tests (id > 2)
    await prisma.visitors.deleteMany({
      where: { id: { gt: 2 } },
    });

    // 7. Equipment generated during tests (id > 2)
    await prisma.equipment.deleteMany({
      where: { id: { gt: 2 } },
    });

    // 8. Vehicles generated during tests (id > 3)
    await prisma.vehicles.deleteMany({
      where: { id: { gt: 3 } },
    });

    // 9. Employees generated during tests (id >= 10)
    await prisma.employees.deleteMany({
      where: { id: { gte: 10 } },
    });

    // 10. Devices provisioned during tests (id > 4 or test name prefixes)
    await prisma.devices.deleteMany({
      where: {
        OR: [
          { id: { gt: 4 } },
          { device_name: { startsWith: "C66_PROV_" } },
          { device_name: { startsWith: "C66_COUNTER_" } },
        ],
      },
    });

    // 11. Reset system lockdown flag to normal operations
    await prisma.site_settings.upsert({
      where: { key: "system_lockdown" },
      create: { key: "system_lockdown", value: "false" },
      update: { value: "false" },
    });
  } catch (err) {
    console.error("Test data cleanup error:", err);
  }
}

