"""Add parsed_qr_data column to gate_logs

Revision ID: 20260507_072643
Revises: 5cbdc2f5e22b
Create Date: 2026-05-07 07:26:43

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20260507_072643'
down_revision = '5cbdc2f5e22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gate_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parsed_qr_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gate_logs', schema=None) as batch_op:
        batch_op.drop_column('parsed_qr_data')
    # ### end Alembic commands ###
