"""Add gate_mappings table for device-to-gate mapping

Revision ID: 20260507_074733
Revises: 20260507_072643
Create Date: 2026-05-07 07:47:33

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260507_074733'
down_revision = '20260507_072643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gate_mappings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ip_address', sa.String(length=50), nullable=False),
        sa.Column('scanner_id', sa.String(length=100), nullable=True),
        sa.Column('gate_name', sa.String(length=100), nullable=False),
        sa.Column('location_description', sa.String(length=200), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('ip_address')
    )
    op.create_index('ix_gate_mappings_ip_address', 'gate_mappings', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gate_mappings_ip_address', table_name='gate_mappings')
    op.drop_table('gate_mappings')
    # ### end Alembic commands ###
